"use client";

import { FormEvent, MouseEvent, useEffect, useState } from "react";
import { CreativeAnnotation, CreativeReview, request, requestBlob } from "@/lib/api";

export default function VisualReview({ projectId, review }: { projectId: string; review: CreativeReview }) {
  const [annotations, setAnnotations] = useState<CreativeAnnotation[]>([]); const [url, setUrl] = useState(""); const [point, setPoint] = useState<{x:number;y:number} | null>(null); const [error, setError] = useState("");
  useEffect(() => { request<CreativeAnnotation[]>(`/api/projects/${projectId}/creative/${review.id}/annotations`).then(setAnnotations).catch(() => setAnnotations([])); }, [projectId, review.id]);
  useEffect(() => { if (!review.content_type.startsWith("image/")) return; let active = true; let objectUrl = ""; requestBlob(`/api/projects/${projectId}/creative/${review.id}/media`).then(blob => { objectUrl = URL.createObjectURL(blob); if (active) setUrl(objectUrl); }).catch(() => null); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [projectId, review]);
  function selectPoint(event: MouseEvent<HTMLDivElement>) { const bounds = event.currentTarget.getBoundingClientRect(); setPoint({ x: Math.round((event.clientX - bounds.left) * 100 / bounds.width), y: Math.round((event.clientY - bounds.top) * 100 / bounds.height) }); }
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; try { const annotation = await request<CreativeAnnotation>(`/api/projects/${projectId}/creative/${review.id}/annotations`, { method: "POST", body: JSON.stringify({ ...Object.fromEntries(new FormData(form)), x: point?.x ?? 50, y: point?.y ?? 50 }) }); setAnnotations(current => [annotation, ...current]); form.reset(); setPoint(null); } catch (error) { setError((error as Error).message); } }
  async function resolve(annotation: CreativeAnnotation, status: "resolved" | "dismissed") { try { const updated = await request<CreativeAnnotation>(`/api/projects/${projectId}/creative/${review.id}/annotations/${annotation.id}`, { method: "PATCH", body: JSON.stringify({ status }) }); setAnnotations(current => current.map(item => item.id === updated.id ? updated : item)); } catch (error) { setError((error as Error).message); } }
  return <section className="visual-review"><p className="eyebrow">Revisión visual</p><p className="muted">{url ? "Hacé clic sobre la imagen para señalar un punto y dejar una devolución." : "Dejá una devolución localizada o general para esta pieza."}</p>{url && <div className="review-canvas" onClick={selectPoint}><img src={url} alt={review.name}/>{annotations.filter(item => item.status === "open").map((item, index) => <i key={item.id} style={{left:`${item.x}%`,top:`${item.y}%`}}>{index + 1}</i>)}{point && <b style={{left:`${point.x}%`,top:`${point.y}%`}}>+</b>}</div>}<form onSubmit={add} className="annotation-form"><div className="field"><label>Observación {point ? `· punto ${point.x}% / ${point.y}%` : "general"}</label><textarea required name="comment" placeholder="Qué debería mantenerse, corregirse o probarse y por qué."/></div><button className="btn ghost">Agregar observación</button></form>{error && <p className="error">{error}</p>}{annotations.length > 0 && <div className="annotation-list">{annotations.map((item, index) => <article key={item.id}><span>{index + 1} · {item.status}</span><p>{item.comment}</p>{item.status === "open" && <div className="row-actions"><button onClick={() => resolve(item, "resolved")}>Resuelta</button><button className="danger-link" onClick={() => resolve(item, "dismissed")}>Descartar</button></div>}</article>)}</div>}</section>;
}
