"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import Nav from "@/components/Nav";
import { BrandAsset, Client, ClientMemory, Project, request } from "@/lib/api";

const fields = [
  ["history", "Historia y relación"], ["products", "Productos y servicios"], ["audiences", "Públicos y ocasiones"], ["competitors", "Competencia y sustitutos"], ["positioning", "Posicionamiento"], ["tone", "Tono y vocabulario"], ["visual_codes", "Códigos visuales y sonoros"], ["restrictions", "Restricciones y obligatorios"], ["approved_patterns", "Aprendizajes aprobados"], ["rejected_patterns", "Enfoques a evitar"], ["commercial_context", "Contexto comercial"], ["territories", "Territorios"], ["notes", "Notas estratégicas"],
];

export default function ClientProfile({ params }: { params: { id: string } }) {
  const [client, setClient] = useState<Client | null>(null); const [memory, setMemory] = useState<ClientMemory | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [assets, setAssets] = useState<BrandAsset[]>([]); const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  const load = async () => { const [clientData, memoryData, projectsData, assetData] = await Promise.all([request<Client[]>("/api/clients").then(items => items.find(item => item.id === params.id) || null), request<ClientMemory>(`/api/clients/${params.id}/memory`), request<Project[]>("/api/projects"), request<BrandAsset[]>(`/api/clients/${params.id}/brand-assets`)]); setClient(clientData); setMemory(memoryData); setProjects(projectsData.filter(project => project.client_id === params.id)); setAssets(assetData); };
  useEffect(() => { load().catch(error => setError(error.message)); }, [params.id]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setSaved(false); try { const data = Object.fromEntries(new FormData(event.currentTarget)); setMemory(await request<ClientMemory>(`/api/clients/${params.id}/memory`, { method: "PUT", body: JSON.stringify({ data }) })); setSaved(true); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  async function uploadAsset(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); if (!data.get("file")) return; setUploading(true); setError(""); try { const asset = await request<BrandAsset>(`/api/clients/${params.id}/brand-assets`, { method: "POST", body: data }); setAssets(current => [asset, ...current]); form.reset(); } catch (error) { setError((error as Error).message); } finally { setUploading(false); } }
  if (!client || !memory) return <main className="shell"><Nav/><p>{error || "Cargando cliente…"}</p></main>;
  return <main className="shell"><Nav/><div className="pagehead"><div><p className="eyebrow">Memoria de cliente · versión {memory.version}</p><h1>{client.name}</h1><p className="muted">{client.industry || "Industria sin definir"}</p></div><div className="page-actions"><Link className="btn ghost" href="/clients">← Clientes</Link><Link className="btn lime" href="/projects/new">Nuevo proyecto</Link></div></div>
    <section className="client-memory-layout"><form className="card memory-form" onSubmit={save}><p className="eyebrow">Memoria estratégica</p><h2>Lo que OLIVA debe recordar</h2><p className="muted">Esta memoria se reutiliza como contexto, nunca como evidencia nueva. Actualizala cuando exista una decisión, aprendizaje o material confirmado.</p>{fields.map(([key, label]) => <div className="field" key={key}><label>{label}</label><textarea name={key} defaultValue={memory.data[key] || ""}/></div>)}<button className="btn lime" disabled={busy}>{busy ? "Guardando…" : "Guardar memoria"}</button>{saved && <p className="success">Memoria actualizada y versionada.</p>}{error && <p className="error">{error}</p>}</form>
      <aside><div className="card brand-dam"><p className="eyebrow">DAM · Activos de marca</p><h2>Logos y referencias visuales</h2><p className="muted">Subí logos, empaques, guías o referencias JPG, PNG o WEBP. El estudio creativo los usa como referencia, sin inventar identidad.</p><form className="compact-form" onSubmit={uploadAsset}><input name="label" placeholder="Ej. Logo principal / pack aprobado" required/><input name="palette" placeholder="Paleta opcional: #78BE36, #454545"/><input name="file" type="file" accept="image/png,image/jpeg,image/webp" required/><button className="btn lime" disabled={uploading}>{uploading ? "Subiendo…" : "Agregar activo"}</button></form>{assets.length === 0 ? <p className="muted">Aún no hay activos cargados.</p> : <div className="brand-assets-list">{assets.map(asset => <a href={`/api/clients/${params.id}/brand-assets/${asset.id}/media`} target="_blank" className="brand-asset" key={asset.id}><img src={`/api/clients/${params.id}/brand-assets/${asset.id}/media`} alt={asset.label}/><span><strong>{asset.label}</strong><small>{asset.palette || "Referencia visual"}</small></span></a>)}</div>}</div><div className="card"><p className="eyebrow">Expediente vivo</p><h2>{projects.length} proyectos</h2>{projects.length === 0 ? <p className="muted">Todavía no hay proyectos asociados.</p> : <div className="library-list">{projects.map(project => <Link className="card nested-card" href={`/projects/${project.id}`} key={project.id}><span className="status">{project.workflow_stage.replaceAll("_", " ")}</span><h3>{project.name}</h3><p className="muted">{project.objective || "Sin objetivo declarado"}</p></Link>)}</div>}</div></aside>
    </section>
  </main>;
}
