"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Nav from "@/components/Nav";
import { ResearchSource, request } from "@/lib/api";

export default function SourcesPage() {
  const [sources, setSources] = useState<ResearchSource[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = () => request<ResearchSource[]>("/api/research-sources").then(setSources);
  useEffect(() => { load().catch(error => setError(error.message)); }, []);
  const countries = useMemo(() => Array.from(new Set(sources.map(source => source.country))), [sources]);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; setBusy(true); setError(""); try { const data = Object.fromEntries(new FormData(form)); await request("/api/research-sources", { method: "POST", body: JSON.stringify({ ...data, priority: Number(data.priority || 2) }) }); form.reset(); await load(); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  async function toggle(source: ResearchSource) { setBusy(true); try { await request(`/api/research-sources/${source.id}`, { method: "PATCH", body: JSON.stringify({ active: !source.active }) }); await load(); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  async function remove(source: ResearchSource) { if (!confirm(`¿Quitar “${source.name}” de las fuentes activas?`)) return; setBusy(true); try { await request(`/api/research-sources/${source.id}`, { method: "DELETE" }); await load(); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  return <main className="shell"><Nav/><section className="radar-hero"><div><p className="eyebrow">Biblioteca Cognitiva · fuentes</p><h1>Fuentes monitoreadas</h1></div><p>Estas fuentes se aplican a la búsqueda web de cada proyecto. Se guardan para el equipo, se pueden pausar y siempre quedan diferenciadas de la evidencia propia del cliente.</p></section>
    <section className="source-summary"><strong>{sources.filter(source => source.active).length} activas</strong><span>{sources.length} fuentes configuradas</span><span>La búsqueda usa las activas según su prioridad.</span></section>
    <section className="source-layout"><aside className="card"><p className="eyebrow">Agregar una fuente</p><h2>Sumar sitio de referencia</h2><form onSubmit={add}><div className="field"><label>Nombre</label><input required name="name" placeholder="Ej. Observatorio de retail"/></div><div className="field"><label>URL</label><input required name="url" type="url" placeholder="https://…"/></div><div className="field two"><div><label>País</label><input name="country" defaultValue="Global"/></div><div><label>Prioridad</label><select name="priority"><option value="1">1 · central</option><option value="2">2 · habitual</option><option value="3">3 · complementaria</option></select></div></div><div className="field"><label>Tipo de información</label><input name="topic" defaultValue="general" placeholder="consumo, medios, creatividad…"/></div><div className="field"><label>Qué aporta</label><textarea name="description" placeholder="Qué clase de información debería buscar OLIVA aquí"/></div><button className="btn lime" disabled={busy}>{busy ? "Guardando…" : "Agregar fuente"}</button></form>{error && <p className="error">{error}</p>}</aside>
      <div className="source-groups">{countries.map(country => <section key={country}><h2>{country}</h2><div className="source-grid">{sources.filter(source => source.country === country).map(source => <article className={`source-card ${source.active ? "" : "inactive"}`} key={source.id}><div><span className="status">prioridad {source.priority}</span><h3>{source.name}</h3><p>{source.description}</p><small>{source.topic} · {source.domain}</small></div><div className="source-actions"><a className="text-action" href={source.url} target="_blank" rel="noreferrer">Abrir ↗</a><button className="text-action" disabled={busy} onClick={() => toggle(source)}>{source.active ? "Pausar" : "Activar"}</button><button className="danger-link" disabled={busy} onClick={() => remove(source)}>{source.is_foundational ? "Quitar" : "Eliminar"}</button></div></article>)}</div></section>)}</div>
    </section></main>;
}
