"use client";

import { FormEvent, useEffect, useState } from "react";
import Nav from "@/components/Nav";
import { Client, Project, request } from "@/lib/api";

export default function NewProject() {
  const [clients, setClients] = useState<Client[]>([]); const [newClient, setNewClient] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { request<Client[]>("/api/clients").then(setClients).catch(error => setError(error.message)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const values = Object.fromEntries(new FormData(event.currentTarget)); let clientId = values.client_id as string; if (newClient.trim()) { const client = await request<Client>("/api/clients", { method: "POST", body: JSON.stringify({ name: newClient.trim() }) }); clientId = client.id; } if (!clientId) throw new Error("Elegí o creá un cliente"); const project = await request<Project>("/api/projects", { method: "POST", body: JSON.stringify({ ...values, client_id: clientId }) }); location.href = `/projects/${project.id}`; } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  return <main className="shell"><Nav/><div className="pagehead"><div><p className="eyebrow">Nuevo expediente</p><h1>Crear proyecto</h1></div></div><form className="card form" onSubmit={submit}><div className="field"><label>Nombre del proyecto</label><input name="name" required placeholder="Ej. Reposicionamiento 2026"/></div><div className="field"><label>Cliente existente</label><select name="client_id"><option value="">Seleccionar…</option>{clients.map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</select></div><div className="field"><label>O crear cliente</label><input value={newClient} onChange={event => setNewClient(event.target.value)} placeholder="Nombre del cliente"/></div><div className="field"><label>Empresa responsable</label><select name="group_company" defaultValue="Oliva Publicidad"><option>Oliva Publicidad</option><option>PUBLInter</option><option>Printshop Carteles</option><option>Veritas Auditor</option></select></div><div className="field two"><div><label>Territorio</label><input name="territory" placeholder="Uruguay, Argentina, departamento…"/></div><div><label>Fecha objetivo</label><input name="deadline" placeholder="Ej. octubre de 2026"/></div></div><div className="field"><label>Participantes internos</label><input name="participants" placeholder="Cuentas, estrategia, creatividad…"/></div><div className="field"><label>Objetivo declarado</label><input name="objective" placeholder="¿Qué necesita lograr la organización?"/></div><div className="field"><label>Brief / contexto</label><textarea name="brief" placeholder="Contanos qué sabemos, qué se pidió y por qué ahora."/></div>{error && <p className="error">{error}</p>}<button className="btn lime" disabled={busy}>{busy ? "Creando…" : "Crear y cargar evidencia →"}</button></form></main>;
}
