"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import Nav from "@/components/Nav";
import { Client, request } from "@/lib/api";

export default function ClientsPage(){
  const [clients,setClients]=useState<Client[]|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const [editing,setEditing]=useState<Client|null>(null);
  const load=()=>request<Client[]>("/api/clients").then(setClients);
  useEffect(()=>{load().catch(error=>setError(error.message))},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=event.currentTarget;try{await request("/api/clients",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function update(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;setBusy(true);setError("");try{await request(`/api/clients/${editing.id}`,{method:"PATCH",body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});setEditing(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function remove(client:Client){if(!confirm(`¿Eliminar “${client.name}”? Esta acción sólo se permite si no tiene proyectos.`))return;setBusy(true);setError("");try{await request(`/api/clients/${client.id}`,{method:"DELETE"});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <main className="shell"><Nav/><div className="pagehead"><div><p className="eyebrow">Directorio de trabajo</p><h1>Clientes</h1></div></div><section className="client-layout"><form className="card" onSubmit={submit}><h2>Nuevo cliente</h2><div className="field"><label>Nombre</label><input name="name" required/></div><div className="field"><label>Industria</label><input name="industry" placeholder="Ej. Alimentos, retail…"/></div><div className="field"><label>Contexto</label><textarea name="description" placeholder="Qué hace la organización, situación y datos relevantes…"/></div><button className="btn lime" disabled={busy}>{busy?"Guardando…":"Crear cliente"}</button></form><div><p className="eyebrow">Directorio</p>{error&&<p className="error">{error}</p>}{clients===null?<p className="muted">Cargando clientes…</p>:<><div className="client-grid">{clients.map(client=><article className="card client-card" key={client.id}>{editing?.id===client.id?<form onSubmit={update}><div className="field"><label>Nombre</label><input name="name" required defaultValue={client.name}/></div><div className="field"><label>Industria</label><input name="industry" defaultValue={client.industry}/></div><div className="field"><label>Contexto</label><textarea name="description" defaultValue={client.description}/></div><div className="inline-actions"><button className="btn lime" disabled={busy}>Guardar</button><button type="button" className="btn ghost" onClick={()=>setEditing(null)}>Cancelar</button></div></form>:<><Link className="text-action" href={`/clients/${client.id}`}>Abrir memoria →</Link><h3>{client.name}</h3><p className="tags">{client.industry||"Industria sin definir"}</p><p className="muted">{client.description||"Sin contexto adicional."}</p><div className="card-actions"><button onClick={()=>setEditing(client)}>Editar</button><button className="danger-link" onClick={()=>remove(client)}>Eliminar</button></div></>}</article>)}</div>{clients.length===0&&<div className="empty small">Todavía no hay clientes.</div>}</>}</div></section></main>
}
